def mostrar_menu():
    return (
        "╭━━━〔 🤖 *AGNES BOT* 🤖 〕━━━╮\n"
        "┃\n"
        "┃  ✨ *Creador:* Jasper\n"
        "┃  📌 *Uso:* Prefijo `.` antes de cada comando\n"
        "┃\n"
        "┣━━ 🎮 *ECONOMÍA & RPG* ━━━\n"
        "┃  • `.trabajar` - Gana monedas\n"
        "┃  • `.daily` - Recompensa diaria\n"
        "┃  • `.cofre` - Abre un cofre sorpresa\n"
        "┃  • `.museo` - Colección de reliquias\n"
        "┃  • `.comprarmuseo` - Adquiere reliquias\n"
        "┃  • `.crimen` - Arriésgate por dinero\n"
        "┃  • `.depositar` / `.retirar` - Banco\n"
        "┃  • `.banco` - Estado de cuenta\n"
        "┃\n"
        "┣━━ ⚡ *POKÉMON* ━━━\n"
        "┃  • `.mispokemon` - Tus pokémones\n"
        "┃  • `.mochila` - Inventario general\n"
        "┃  • `.tiendapokemon` - Tienda oficial\n"
        "┃  • `.capturar` - Atrapa un pokémon\n"
        "┃  • `.toppokemon` - Pokémon favorito\n"
        "┃\n"
        "┣━━ 👤 *PERFIL DE USUARIO* ━━━\n"
        "┃  • `.perfil` - Tarjeta de presentación\n"
        "┃  • `.level` - Tu nivel actual\n"
        "┃  • `.setname` - Cambiar nombre\n"
        "┃  • `.setgene` - Configurar género\n"
        "┃  • `.setage` - Configurar edad\n"
        "┃  • `.setbirth` - Fecha de nacimiento\n"
        "┃  • `.setdesc` - Biografía del perfil\n"
        "┃\n"
        "┣━━ 📥 *DESCARGAS MULTIMEDIA* ━━━\n"
        "┃  • `.descargar` - Enlace general\n"
        "┃  • `.mediafire` / `.mega` - Archivos\n"
        "┃  • `.facebook` / `.instagram` - Redes\n"
        "┃  • `.tiktok` / `.youtube` - Videos\n"
        "┃  • `.imagen` - Buscar imágenes\n"
        "┃  • `.pin` - Buscar en Pinterest\n"
        "┃\n"
        "┣━━ 🎭 *INTERACCIONES* ━━━\n"
        "┃  *(⚠️ En mantenimiento temporal)*\n"
        "┃  • `.saludar` • `.beso` • `.abrazo`\n"
        "┃  • `.golpe` • `.kill` • `.caricia` • `.correr`\n"
        "┃\n"
        "┣━━ ⚙️ *GESTIÓN DE GRUPOS* ━━━\n"
        "┃  • `.welcome` - Activa/desactiva bienvenida\n"
        "┃  • `.reglas` - Normas del grupo\n"
        "┃\n"
        "┣━━ 🛡️ *ADMINISTRACIÓN* ━━━\n"
        "┃  • `.adminmenu` - Panel exclusivo\n"
        "┃\n"
        "╰━━━━━━━━━━━━━━━━━━━━━━╯"
    )
